site_name: autisticstuff
site_description: "...autisticstuff?"
site_url: https://twohundredpointsonraads.github.io/autisticstuff

repo_url: https://github.com/twohundredpointsonraads/autisticstuff
repo_name: twohundredpointsonraads/autisticstuff
edit_uri: edit/main/docs/

docs_dir: docs
site_dir: site
strict: false

nav:
  - Home: index.md
  - Getting Started:
      - Overview: getting-started/overview.md
      - Installation: getting-started/installation.md
      - Usage: getting-started/usage.md
  - Reference:
      - API Reference: reference/index.md
  - Changelog: changelog.md

theme: mkdocs

plugins:
  - search
  # Uncomment mkdocstrings for Python API docs (requires: pip install mkdocstrings[python])
  # - mkdocstrings:
  #     default_handler: python
  #     handlers:
  #       python:
  #         paths: ["."]
  #         options:
  #           show_source: true
  #           show_signature: true
  #           separate_signature: true
  #           members_order: alphabetical

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  # For emoji below, mkdocs-material must be installed
  # - pymdownx.emoji:
    #   emoji_generator: !!python/name:materialx.emoji.to_svg
    #   emoji_index: !!python/name:materialx.emoji.twemoji

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/twohundredpointsonraads/autisticstuff
  generator: false

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

watch:
  - overrides
