site_name: autisticstuff
site_description: "...autisticstuff?"
site_url: https://twohundredpointsonraads.github.io/autisticstuff

repo_url: https://github.com/twohundredpointsonraads/autisticstuff
repo_name: twohundredpointsonraads/autisticstuff
edit_uri: edit/main/docs/

docs_dir: .
site_dir: ../site
strict: false

nav:
  - Home: index.md
  - Getting Started:
      - Overview: getting-started/overview.md
      - Installation: getting-started/installation.md
      - Usage: getting-started/usage.md
  - Reference:
      - API Reference: reference/index.md
  - Changelog: changelog.md

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
       python:
          paths: ["."]
          options:
            show_source: true
            show_signature: true
            separate_signature: true
            members_order: alphabetical

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/twohundredpointsonraads/autisticstuff
  generator: false

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

watch:
  - overrides
