name: bump
author: plassstic
description: bump
inputs:
  app-id: 
    required: true
    description: "appid"
  private-key:
    required: true
    description: "pkey"
runs:
  using: composite
  steps:
    - uses: actions/create-github-app-token@v2.1.1
      id: app-token
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ steps.app-token.outputs.token }}
    
    - name: Get GitHub App User ID
      id: get-user-id
      run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
      shell: bash
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}

    - name: git
      shell: bash
      run: |
        git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
        git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
      
    - name: get version from tag
      env:
        LIBVER: ${{ github.ref }}
      run: |
        LIBVER=${{ env.LIBVER }}
        LIBVER=${LIBVER#refs/tags/v}
        echo LIBVER=${LIBVER} >> $GITHUB_ENV
      shell: bash
      
    - name: install uv
      uses: astral-sh/setup-uv@v6
      
    - name: bump version in package according to tag
      run: uv version ${{ env.LIBVER }}
      shell: bash
      
    - name: bump version and push
      run: |
        git remote set-url origin https://x-access-token:${{ steps.generate_token.outputs.token }}@github.com/${{ github.repository }}.git
        
        git add .
        if ! git diff --staged --quiet; then
          git commit -m "v${{ env.LIBVER }}"
          git push origin HEAD:main
        else
          echo "No changes to commit"
        fi
      shell: bash