name: publish

permissions:
  id-token: write

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: install uv pacman
        uses: astral-sh/setup-uv@v6
      - name: sync dependencies
        run: make sync
      - name: build pkg
        run: make build

  publish-test:
    needs: build-test
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: install uv pacman
        uses: astral-sh/setup-uv@v6
      - name: sync
        run: make sync
      - name: build pkg
        run: make build
      - name: testpypi publish
        run: make publish-test

  publish:
    needs: build-test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: install uv pacman
        uses: astral-sh/setup-uv@v6
      - name: sync
        run: make sync
      - name: get version from tag
        env:
          LIBVER: ${{ github.ref }}
        run: |
          LIBVER=${{ env.LIBVER }}
          LIBVER=${LIBVER#refs/tags/v}
          echo LIBVER=${LIBVER} >> $GITHUB_ENV
      - name: bump version according to tag
        run: uv version ${{ env.LIBVER }}
      - name: build pkg
        run: make build
      - name: pypi publish
        run: make publish
