name: publish

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish-test:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/autisticstuff
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - name: build pkg
        uses: ./.github/actions/build
      - name: dl build
        uses: actions/download-artifact@v5
        with:
          name: build-dist
          path: dist/
      - name: testpypi upl
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/


  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/autisticstuff
    steps:
      - uses: actions/checkout@v5
      - name: bump ver
        uses: ./.github/actions/bump
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@v5
      - name: build pkg
        uses: ./.github/actions/build
      - name: dl build
        uses: actions/download-artifact@v5
        with:
          name: build-dist
          path: dist/
      - name: pypi upl
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/
